server:
  port: 7777

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    user:
      name: guest
      password: 12345

api-service-base-url: http://localhost:8080
