server:
  port: 7777

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    user:
      name: admin
      password: $2a$10$d1U9uZLLiePh.3bqSexYxeYSbHaCUWcTiDV6klOeTLcp5rAz38aeW  # 12345
      roles: admin

api-service:
  base-url: http://localhost:8080
